spring.application.name=guildboard

spring.datasource.url=jdbc:postgresql://<IP_ADRESS>:5432/<DATABASE_NAME>
spring.datasource.username=<USER>
spring.datasource.password=<PASSWORD>
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true