spring.application.name=guildboard

spring.datasource.url=jdbc:postgresql://localhost:5432/guildboard
spring.datasource.username=postgres
spring.datasource.password=1234
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

management.endpoints.web.exposure.include=health,info,metrics,env,loggers
management.endpoint.health.show-details=always
management.info.build.enabled=true